### ISSUE TITLE
texture2D unsupported in core profile

### ISSUE THREAD

**Issue by grondag** [Poisoned-Honey/HoneyShaders#1]
`texture2D` is no longer supported in OpenGL core profile.  Some drivers will still accept it, some will warn, and some will outright file.  (MacOS and linux tend to be more strict - HoneyShaders currently won't run at all there.)

This can usually be resolved simply by replacing `texture2d` with `texture`.

**Comment by ambrosia13** [comment]
I... was completely unaware of this change. Thank you very much for letting me know about this. it's fixed.
